<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

         //For home modual

        // For areas Modual
        $Permissions = new \App\Permission();
        $Permissions->name="areas.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="area";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="areas.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="area";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="areas.store";
        $Permissions->description="Can Add Area";
        $Permissions->modual="area";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="areas.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="area";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="areas.update";
        $Permissions->description="Update area";
        $Permissions->modual="area";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="areas.edit";
        $Permissions->description="Only show edit form";
        $Permissions->modual="area";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="areas.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="area";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="areas.getDataForDataTable";
        $Permissions->description="Show Area List";
        $Permissions->modual="area";
        $Permissions->Save();

        // For branches Modual
        $Permissions = new \App\Permission();
        $Permissions->name="branches.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="branch";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="branches.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="branch";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="branches.store";
        $Permissions->description="Can Add Branch";
        $Permissions->modual="branch";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="branches.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="branch";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="branches.edit";
        $Permissions->description="Only show Edit date";
        $Permissions->modual="branch";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="branches.update";
        $Permissions->description="Update branches";
        $Permissions->modual="branch";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="branches.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="branch";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="branches.getDataForDataTable";
        $Permissions->description="Show Branch List";
        $Permissions->modual="branch";
        $Permissions->Save();

        // For sessions Modual
        $Permissions = new \App\Permission();
        $Permissions->name="sessions.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="session";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sessions.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="session";
        $Permissions->Save();
         $Permissions = new \App\Permission();
        $Permissions->name="sessions.store";
        $Permissions->description="Can Add Session";
        $Permissions->modual="session";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sessions.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="session";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sessions.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="session";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sessions.update";
        $Permissions->description="update sessions";
        $Permissions->modual="session";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sessions.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="session";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sessions.getDataForDataTable";
        $Permissions->description="Show Session List";
        $Permissions->modual="session";
        $Permissions->Save();

        // For terms Modual
        $Permissions = new \App\Permission();
        $Permissions->name="terms.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="term";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="terms.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="term";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="terms.store";
        $Permissions->description="Can Add Term";
        $Permissions->modual="term";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="terms.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="term";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="terms.edit";
        $Permissions->description="show edit terms";
        $Permissions->modual="term";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="terms.update";
        $Permissions->description="update term";
        $Permissions->modual="term";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="terms.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="term";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="terms.getDataForDataTable";
        $Permissions->description="Show Term List";
        $Permissions->modual="term";
        $Permissions->Save();

        // For shifts Modual
        $Permissions = new \App\Permission();
        $Permissions->name="shifts.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="shift";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="shifts.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="shift";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="shifts.store";
        $Permissions->description="Can Add Shift";
        $Permissions->modual="shift";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="shifts.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="shift";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="shifts.edit";
        $Permissions->description="show edit data";
        $Permissions->modual="shift";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="shifts.update";
        $Permissions->description="show shifts";
        $Permissions->modual="shift";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="shifts.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="shift";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="shifts.getDataForDataTable";
        $Permissions->description="Show Shift List";
        $Permissions->modual="shift";
        $Permissions->Save();

        // For teachers Modual
        $Permissions = new \App\Permission();
        $Permissions->name="teachers.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="teachers.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="teachers.store";
        $Permissions->description="Can Add Teacher";
        $Permissions->modual="teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="teachers.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="teachers.edit";
        $Permissions->description="show edit data";
        $Permissions->modual="teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="teachers.update";
        $Permissions->description="update teacher";
        $Permissions->modual="teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="teachers.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="teacher";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="teachers.getDataForDataTable";
        $Permissions->description="Show Teachers List";
        $Permissions->modual="teacher";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="teachers.changePassword";
        $Permissions->description="Change Teachers Password";
        $Permissions->modual="teacher";
        $Permissions->Save();

        // For Class Modual
        $Permissions = new \App\Permission();
        $Permissions->name="levels.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="level";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levels.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="level";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levels.store";
        $Permissions->description="Can Add Levels";
        $Permissions->modual="level";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levels.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="level";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levels.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="level";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levels.update";
        $Permissions->description="update levels";
        $Permissions->modual="level";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levels.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="level";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levels.getDataForDataTable";
        $Permissions->description="Show List of Levels";
        $Permissions->modual="level";
        $Permissions->Save();

        // For sections Modual
        $Permissions = new \App\Permission();
        $Permissions->name="sections.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="section";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sections.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="section";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sections.store";
        $Permissions->description="Can Add Section";
        $Permissions->modual="section";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sections.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="section";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sections.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="section";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sections.update";
        $Permissions->description="update section";
        $Permissions->modual="section";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sections.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="section";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sections.getDataForDataTable";
        $Permissions->description="Section List";
        $Permissions->modual="section";
        $Permissions->Save();

        // For students Modual
        $Permissions = new \App\Permission();
        $Permissions->name="students.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="students.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="students.store";
        $Permissions->description="Can Add Student";
        $Permissions->modual="student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="students.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="students.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="students.update";
        $Permissions->description="update student";
        $Permissions->modual="student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="students.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="students.getDataForDataTable";
        $Permissions->description="Show List of Students";
        $Permissions->modual="student";
        $Permissions->Save();

        // For subjects Modual
        $Permissions = new \App\Permission();
        $Permissions->name="subjects.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="subject";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="subjects.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="subject";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="subjects.store";
        $Permissions->description="Can Add Subject";
        $Permissions->modual="subject";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="subjects.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="subject";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="subjects.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="subject";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="subjects.update";
        $Permissions->description="update subject";
        $Permissions->modual="subject";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="subjects.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="subject";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="subjects.getDataForDataTable";
        $Permissions->description="Show List of Subjects";
        $Permissions->modual="subject";
        $Permissions->Save();
       
        //For Result Module
        $Permissions = new \App\Permission();
        $Permissions->name="results.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.create";
        $Permissions->description="Can View Form";
        $Permissions->modual="result";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="results.store";
        $Permissions->description="Can Add Result";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="result";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="results.update";
        $Permissions->description="update result";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.getDataForDataTable";
        $Permissions->description="Show Result List";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.viewByNumber";
        $Permissions->description="View Results By Number";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.chooseNumber";
        $Permissions->description="Choose Number for Result";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.weeklyResult";
        $Permissions->description="View Weekly Result";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.showSubjects";
        $Permissions->description="Show Subjects in Result";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.chooseTestNumber";
        $Permissions->description="Choose Test Number";
        $Permissions->modual="result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="results.showResult";
        $Permissions->description="Show Result";
        $Permissions->modual="result";
        $Permissions->Save();

        //For Level Enrolls
        $Permissions = new \App\Permission();
        $Permissions->name="levelEnrolls.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="levelEnroll";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levelEnrolls.create";
        $Permissions->description="Can View Form";
        $Permissions->modual="levelEnroll";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levelEnrolls.store";
        $Permissions->description="Can Add Level Enroll";
        $Permissions->modual="levelEnroll";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levelEnrolls.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="levelEnroll";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levelEnrolls.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="levelEnroll";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levelEnrolls.update";
        $Permissions->description="update levelEnroll";
        $Permissions->modual="levelEnroll";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levelEnrolls.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="levelEnroll";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levelEnrolls.getDataForDataTable";
        $Permissions->description="Show Level Enroll List";
        $Permissions->modual="levelEnroll";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="levels.enrollment";
        $Permissions->description="Assign Enroll";
        $Permissions->modual="levelEnroll";
        $Permissions->Save();

        // For Weekly Test Modual
        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklytests.index";
        // $Permissions->description="All Data Views";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();
        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklytests.edit";
        // $Permissions->description="Only show edit data";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();
        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklytests.update";
        // $Permissions->description="update Weekly test marks";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklytests.destroy";
        // $Permissions->description="Delete  Weekly test marks";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.showSubjects";
        // $Permissions->description="Show Subjects In WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.proceedWithSubject";
        // $Permissions->description="Proceed With Subject In WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.proceedWithTestNumber";
        // $Permissions->description="Proceed With Number In WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.subjectWiseResult";
        // $Permissions->description="Subject Wise Result In WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.viewSubjectWiseResult";
        // $Permissions->description="Subject Wise Result In WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.viewNumberWiseResult";
        // $Permissions->description="Number Wise Result In WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.updateMarks";
        // $Permissions->description="Update Mark In WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.deleteResult";
        // $Permissions->description="Delete Result Of WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();


        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.storeMarks";
        // $Permissions->description="Save Marks Of WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();


        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.viewStudentWiseResult";
        // $Permissions->description="Student Wise Result Of WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="weeklyTests.generateTermResult";
        $Permissions->description="Generate Term Result";
        $Permissions->modual="Term Result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="weeklyTests.reGenerateTermResult";
        $Permissions->description="Re Generate Term Result";
        $Permissions->modual="Term Result";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="weeklyTests.viewTermResult";
        $Permissions->description="View Term Result of WT";
        $Permissions->modual="Term Result";
        $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklytests.downloadPDF";
        // $Permissions->description="PDF Result of WT";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklytests.download_wt_pdf";
        // $Permissions->description="Download WT Result";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        //For Report View Modual
        $Permissions = new \App\Permission();
        $Permissions->name="weeklyTests.viewTermReport";
        $Permissions->description="View Term Report";
        $Permissions->modual="Term Result";
        $Permissions->Save();

        // $Permissions = new \App\Permission();
        // $Permissions->name="weeklyTests.reportWeeklyTest";
        // $Permissions->description="View Weekly Test Report";
        // $Permissions->modual="weekly test";
        // $Permissions->Save();

        //For Term Result Module
        $Permissions = new \App\Permission();
        $Permissions->name="termresults.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="Term Result";
        $Permissions->Save();

        // For SectionStudents Modual
        $Permissions = new \App\Permission();
        $Permissions->name="sectionStudents.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="section Student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionStudents.create";
        $Permissions->description="Only Can Create";
        $Permissions->modual="section Student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionStudents.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="section Student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionStudents.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="section Student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionStudents.update";
        $Permissions->description="update section students";
        $Permissions->modual="section Student";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionStudents.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="section Student";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="weeklytests.getDataForDataTable";
        $Permissions->description="View Student Section";
        $Permissions->modual="section Student";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="sections.assignStudent";
        $Permissions->description="Assign Students to Section";
        $Permissions->modual="section Student";
        $Permissions->Save();


        $Permissions = new \App\Permission();
        $Permissions->name="sectionStudents.getDataForDataTable";
        $Permissions->description="Show List of Section Students";
        $Permissions->modual="section Student";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="sections.saveStudents";
        $Permissions->description="Save Students to Sections";
        $Permissions->modual="section Student";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="sections.assignSubject";
        $Permissions->description="Assign Subject to Section";
        $Permissions->modual="section Student";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="sections.saveSubject";
        $Permissions->description="Save Subject to Sections";
        $Permissions->modual="section Student";
        $Permissions->Save();


         // For sectionSubjectTeachers Modual
        $Permissions = new \App\Permission();
        $Permissions->name="sectionSubjectTeachers.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="Subject Teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionSubjectTeachers.create";
        $Permissions->description="Only Can Create";
        $Permissions->modual="Subject Teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionSubjectTeachers.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="Subject Teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionSubjectTeachers.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="Subject Teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionSubjectTeachers.update";
        $Permissions->description="update subject teachers";
        $Permissions->modual="Subject Teacher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionSubjectTeachers.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="Subject Teacher";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="sectionSubjectTeachers.getDataForDataTable";
        $Permissions->description="View List of Teachers";
        $Permissions->modual="Subject Teacher";
        $Permissions->Save();


        // For accounts Modual
        $Permissions = new \App\Permission();
        $Permissions->name="accounts.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="account";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="accounts.create";
        $Permissions->description="Only Can Create";
        $Permissions->modual="account";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="accounts.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="account";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="accounts.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="account";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="accounts.update";
        $Permissions->description="update account";
        $Permissions->modual="account";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="accounts.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="account";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="accounts.getDataForDataTable";
        $Permissions->description="View List of Accounts";
        $Permissions->modual="account";
        $Permissions->Save();

           // For Final Reports Modual
      /*  $Permissions = new \App\Permission();
        $Permissions->name="final_reports.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="final report";
        $Permissions->Save();*/

        $Permissions = new \App\Permission();
        $Permissions->name="finalReports.viewStudents";
        $Permissions->description="View Students in Final Report";
        $Permissions->modual="final report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="finalReports.processStudents";
        $Permissions->description="Process Students";
        $Permissions->modual="final report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="finalReports.reProcessStudents";
        $Permissions->description="Re Process Students";
        $Permissions->modual="final report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="finalReports.processSpecificStudents";
        $Permissions->description="Process Specific Students";
        $Permissions->modual="final report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="finalReports.reportPdfFinal";
        $Permissions->description="View Final Report";
        $Permissions->modual="final report";
        $Permissions->Save();


        // For reports Modual
        $Permissions = new \App\Permission();
        $Permissions->name="reports.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="report";
        $Permissions->Save();
        /*$Permissions = new \App\Permission();
        $Permissions->name="reportPdfFinal";
        $Permissions->description="Export Student Final Result";
        $Permissions->modual="report";
        $Permissions->Save();*/
        $Permissions = new \App\Permission();
        $Permissions->name="reports.create";
        $Permissions->description="Only Can Create";
        $Permissions->modual="report";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="reports.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="report";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="reports.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="report";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="reports.update";
        $Permissions->description="update report";
        $Permissions->modual="report";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="reports.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="report";
        $Permissions->Save();

        // For Fiscal Year Modual
        $Permissions = new \App\Permission();
        $Permissions->name="fiscal_years.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="fiscal year";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fiscal_years.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="fiscal year";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fiscal_years.store";
        $Permissions->description="Can Add Fiscal Year";
        $Permissions->modual="fiscal year";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fiscal_years.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="fiscal year";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fiscal_years.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="fiscal year";
        $Permissions->Save();
         $Permissions = new \App\Permission();
        $Permissions->name="fiscal_years.update";
        $Permissions->description="update fiscal year";
        $Permissions->modual="fiscal year";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fiscal_years.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="fiscal year";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fiscalYears.getDataForDataTable";
        $Permissions->description="Show Fiscal List";
        $Permissions->modual="fiscal year";
        $Permissions->Save();
        // For Business Month Modual
        $Permissions = new \App\Permission();
        $Permissions->name="business_months.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="business month";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="business_months.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="business month";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="business_months.store";
        $Permissions->description="Can Add Business Months";
        $Permissions->modual="business month";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="business_months.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="business month";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="business_months.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="business month";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="business_months.update";
        $Permissions->description="update business month";
        $Permissions->modual="business month";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="business_months.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="business month";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="businessMonths.getMonthDataForDataTable";
        $Permissions->description="Show Business Months List";
        $Permissions->modual="business month";
        $Permissions->Save();
        // For prefixes Modual
        $Permissions = new \App\Permission();
        $Permissions->name="prefixes.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="prefix";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="prefixes.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="prefix";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="prefixes.store";
        $Permissions->description="Can Add Prefix";
        $Permissions->modual="prefix";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="prefixes.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="prefix";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="prefixes.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="prefix";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="prefixes.update";
        $Permissions->description="update prefix";
        $Permissions->modual="prefix";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="prefixes.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="prefix";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="prefixes.getDataForDataTable";
        $Permissions->description="Show Prefix List";
        $Permissions->modual="prefix";
        $Permissions->Save();

        // For Fees Books Modual
        $Permissions = new \App\Permission();
        $Permissions->name="fees_books.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="fees book";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_books.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="fees book";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_books.store";
        $Permissions->description="Can Add Fees Books";
        $Permissions->modual="fees book";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_books.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="fees book";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_books.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="fees book";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_books.update";
        $Permissions->description="update fees book";
        $Permissions->modual="fees book";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_books.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="fees book";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="feesBooks.getDataForDataTable";
        $Permissions->description="Show List of Fees Books";
        $Permissions->modual="fees book";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="feesBooks.checkPrefixLeaf";
        $Permissions->description="Check Prefix Leaf";
        $Permissions->modual="fees book";
        $Permissions->Save();

        // For Fees Type Modual
        $Permissions = new \App\Permission();
        $Permissions->name="fees_types.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="fees type";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_types.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="fees type";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_types.store";
        $Permissions->description="Can Add Fees Type";
        $Permissions->modual="fees type";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_types.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="fees type";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_types.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="fees type";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_types.update";
        $Permissions->description="update fees type";
        $Permissions->modual="fees type";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="fees_types.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="fees type";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="feesTypes.getDataForDataTable";
        $Permissions->description="Show Fees Type List";
        $Permissions->modual="fees type";
        $Permissions->Save();

        // For section Wise Fees Modual
        $Permissions = new \App\Permission();
        $Permissions->name="section_wise_fees.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="section wise fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="section_wise_fees.create";
        $Permissions->description="Can Show Add Form";
        $Permissions->modual="section wise fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="section_wise_fees.store";
        $Permissions->description="Can Add Section Wise Fee";
        $Permissions->modual="section wise fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="section_wise_fees.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="section wise fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="section_wise_fees.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="section wise fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="section_wise_fees.update";
        $Permissions->description="update section fee";
        $Permissions->modual="section wise fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="section_wise_fees.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="section wise fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="sectionWiseFees.getDataForDataTable";
        $Permissions->description="Show Section Wise Fees";
        $Permissions->modual="section wise fees";
        $Permissions->Save();

        // For Payment Method Modual
        $Permissions = new \App\Permission();
        $Permissions->name="payment_methods.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="payment method";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="payment_methods.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="payment method";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="payment_methods.store";
        $Permissions->description="Can Add Payment Method";
        $Permissions->modual="payment method";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="payment_methods.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="payment method";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="payment_methods.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="payment method";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="payment_methods.update";
        $Permissions->description="update payment method";
        $Permissions->modual="payment method";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="payment_methods.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="payment method";
        $Permissions->Save();

        // For Collect Fees Modual
        $Permissions = new \App\Permission();
        $Permissions->name="collected_fees.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="collected fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="collected_fees.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="collected fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="collected_fees.store";
        $Permissions->description="Can Add Collected Fees";
        $Permissions->modual="collected fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="collected_fees.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="collected fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="collected_fees.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="collected fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="collected_fees.update";
        $Permissions->description="update collected fees";
        $Permissions->modual="collected fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="collected_fees.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="collected fees";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="paymentMethods.getDataForDataTable";
        $Permissions->description="Show Payment Method List";
        $Permissions->modual="collected fees";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="collectedFees.pdfInvoice";
        $Permissions->description="Show PDF Invoice";
        $Permissions->modual="collected fees";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="collectedFees.calculateFees";
        $Permissions->description="Calculate Fees";
        $Permissions->modual="collected fees";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="collectedFees.getDataForDataTable";
        $Permissions->description="Show Collected Fees List";
        $Permissions->modual="collected fees";
        $Permissions->Save();



        // For categories Modual
        $Permissions = new \App\Permission();
        $Permissions->name="categories.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="category";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="categories.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="category";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="categories.store";
        $Permissions->description="Can Add Categories";
        $Permissions->modual="category";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="categories.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="category";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="categories.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="category";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="categories.update";
        $Permissions->description="update category";
        $Permissions->modual="category";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="categories.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="category";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="categories.getDataForDataTable";
        $Permissions->description="Show Category List";
        $Permissions->modual="category";
        $Permissions->Save();

        // For suppliers Modual
        $Permissions = new \App\Permission();
        $Permissions->name="suppliers.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="supplier";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="suppliers.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="supplier";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="suppliers.store";
        $Permissions->description="Only Add Suppliers";
        $Permissions->modual="supplier";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="suppliers.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="supplier";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="suppliers.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="supplier";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="suppliers.update";
        $Permissions->description="update supplier";
        $Permissions->modual="supplier";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="suppliers.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="supplier";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="suppliers.getDataForDataTable";
        $Permissions->description="Show Supllier List";
        $Permissions->modual="supplier";
        $Permissions->Save();

        // For vouchers Modual
        $Permissions = new \App\Permission();
        $Permissions->name="vouchers.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="voucher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="vouchers.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="voucher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="vouchers.store";
        $Permissions->description="Can Add Vouchers";
        $Permissions->modual="voucher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="vouchers.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="voucher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="vouchers.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="voucher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="vouchers.update";
        $Permissions->description="update voucher";
        $Permissions->modual="voucher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="vouchers.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="voucher";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="vouchers.getDataForDataTable";
        $Permissions->description="Show Voucher List";
        $Permissions->modual="voucher";
        $Permissions->Save();
        
        // For Finacial reports Modual
        $Permissions = new \App\Permission();
        $Permissions->name="financial_reports.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="financial report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="financial_reports.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="financial report";
        $Permissions->Save();
      
        $Permissions = new \App\Permission();
        $Permissions->name="financialReports.generate_report";
        $Permissions->description="Generate Financial Report";
        $Permissions->modual="financial report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="financialReports.monthWiseReport";
        $Permissions->description="View Month wise Report";
        $Permissions->modual="financial report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="financialReports.yearWiseReport";
        $Permissions->description="View Year wise Report";
        $Permissions->modual="financial report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="financialReports.studentWiseReport";
        $Permissions->description="View Student wise Report";
        $Permissions->modual="financial report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="finalReports.getDataForDataTable";
        $Permissions->description="View Final Report";
        $Permissions->modual="financial report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="finalReports.studentWiseReportView";
        $Permissions->description="View Student Wise Report";
        $Permissions->modual="financial report";
        $Permissions->Save();

        // For roles Modual
        $Permissions = new \App\Permission();
        $Permissions->name="roles.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="role";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="roles.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="role";
        $Permissions->Save();
         $Permissions = new \App\Permission();
        $Permissions->name="roles.store";
        $Permissions->description="Can Add Role";
        $Permissions->modual="role";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="roles.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="role";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="roles.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="role";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="roles.update";
        $Permissions->description="update role";
        $Permissions->modual="role";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="roles.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="role";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="roles.getDataForDataTable";
        $Permissions->description="Show Role List";
        $Permissions->modual="role";
        $Permissions->Save();

        // For Permissions Modual
        $Permissions = new \App\Permission();
        $Permissions->name="permissions.index";
        $Permissions->description="All Data Views";
        $Permissions->modual="permission";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="permissions.create";
        $Permissions->description="Can View Add Form";
        $Permissions->modual="permission";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="permissions.store";
        $Permissions->description="Can Add Permissions";
        $Permissions->modual="permission";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="permissions.show";
        $Permissions->description="Only Can Read";
        $Permissions->modual="permission";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="permissions.edit";
        $Permissions->description="Only show edit data";
        $Permissions->modual="permission";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="permissions.update";
        $Permissions->description="update permission";
        $Permissions->modual="permission";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="permissions.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="permission";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="permissions.getDataForDataTable";
        $Permissions->description="Show Permission List";
        $Permissions->modual="permission";
        $Permissions->Save();

        // For Users Modual
        $Permissions = new \App\Permission();
        $Permissions->name="users.index";
        $Permissions->description="All Data Page";
        $Permissions->modual="user";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="users.create";
        $Permissions->description="Can View User Add Form";
        $Permissions->modual="user";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="users.store";
        $Permissions->description="Can Add User";
        $Permissions->modual="user";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="users.show";
        $Permissions->description="Can View Profile";
        $Permissions->modual="user";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="users.edit";
        $Permissions->description="Only show Edit data";
        $Permissions->modual="user";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="users.update";
        $Permissions->description="Update user data";
        $Permissions->modual="user";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="users.destroy";
        $Permissions->description="Only Can Delete";
        $Permissions->modual="user";
        $Permissions->Save();
        $Permissions = new \App\Permission();
        $Permissions->name="users.getDataForDataTable";
        $Permissions->description="Show User List";
        $Permissions->modual="user";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name="users.changePassword";
        $Permissions->description="Can Change Password";
        $Permissions->modual="user";
        $Permissions->Save();


        //final report modual
        $Permissions = new \App\Permission();
        $Permissions->name = "finalReportStudent";
        $Permissions->description="Final Report Student";
        $Permissions->modual="final report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name = "final_reports.index";
        $Permissions->description="Final Reports";
        $Permissions->modual="final report";
        $Permissions->Save();  

        $Permissions = new \App\Permission();
        $Permissions->name = "final_reports.show";
        $Permissions->description="Final Reports show";
        $Permissions->modual="final report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name = "processFinalReports";
        $Permissions->description="Process Final Reports";
        $Permissions->modual="final report";
        $Permissions->Save();

        $Permissions = new \App\Permission();
        $Permissions->name = "reports.weeklyTest";
        $Permissions->description="View Final Reports";
        $Permissions->modual="final report";
        $Permissions->Save();
    }
}
